#!/usr/bin/env bash
#
# Local PR Review Script
# Review a GitHub PR locally using Copilot CLI
#
# Usage:
#   ./scripts/review-local.sh <pr-number> [repo]
#   ./scripts/review-local.sh 123
#   ./scripts/review-local.sh 123 owner/repo
#
set -euo pipefail

# Load .env if exists
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

if [[ -f "$PROJECT_ROOT/.env" ]]; then
    # shellcheck disable=SC1091
    source "$PROJECT_ROOT/.env"
fi

# Configuration
PR_NUMBER="${1:-}"
GITHUB_REPOSITORY="${2:-${GITHUB_REPOSITORY:-}}"
COPILOT_MODEL="${COPILOT_MODEL:-claude-sonnet-4}"
POST_COMMENT="${POST_COMMENT:-false}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $*"; }

# Validate inputs
if [[ -z "$PR_NUMBER" ]]; then
    echo "Usage: $0 <pr-number> [owner/repo]"
    echo ""
    echo "Examples:"
    echo "  $0 123                    # Review PR #123 in current repo"
    echo "  $0 123 owner/repo         # Review PR #123 in specified repo"
    echo ""
    echo "Environment variables:"
    echo "  COPILOT_GITHUB_TOKEN     Required: Fine-grained PAT with Copilot access"
    echo "  GITHUB_REPOSITORY        Default repo (owner/repo format)"
    echo "  COPILOT_MODEL            AI model (default: claude-sonnet-4)"
    echo "  POST_COMMENT             Set to 'true' to post comment to PR"
    exit 1
fi

# Auto-detect repo from git remote if not specified
if [[ -z "$GITHUB_REPOSITORY" ]]; then
    GITHUB_REPOSITORY=$(git remote get-url origin 2>/dev/null | sed -E 's/.*github\.com[:/]([^/]+\/[^/.]+)(\.git)?$/\1/' || true)
fi

if [[ -z "$GITHUB_REPOSITORY" ]]; then
    log_error "Could not determine repository. Specify as second argument or set GITHUB_REPOSITORY"
    exit 1
fi

# Check for token
if [[ -z "${COPILOT_GITHUB_TOKEN:-}" ]]; then
    log_error "COPILOT_GITHUB_TOKEN is required"
    echo "Create a Fine-Grained PAT at https://github.com/settings/personal-access-tokens/new"
    echo "with 'Copilot Requests: Read' permission"
    exit 1
fi

export COPILOT_GITHUB_TOKEN

log_info "Reviewing PR #${PR_NUMBER} in ${GITHUB_REPOSITORY}"
log_info "Model: ${COPILOT_MODEL}"

# Fetch PR diff
log_step "Fetching PR diff..."

# Use gh CLI if available, otherwise curl
if command -v gh &> /dev/null; then
    DIFF=$(gh pr diff "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" 2>/dev/null || true)
else
    DIFF=$(curl -sL \
        -H "Accept: application/vnd.github.v3.diff" \
        -H "Authorization: Bearer ${COPILOT_GITHUB_TOKEN}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}")
fi

if [[ -z "$DIFF" || "$DIFF" == "null" ]]; then
    log_error "Failed to fetch PR diff. Check PR number and repository."
    exit 1
fi

DIFF_SIZE=${#DIFF}
log_info "Diff size: ${DIFF_SIZE} characters"

# Generate review prompt
PROMPT="You are a senior software engineer performing a code review. Analyze the following git diff and provide a thorough code review.

Focus on:
1. **Bugs & Issues**: Potential bugs, logic errors, or runtime issues
2. **Security**: Security vulnerabilities or concerns
3. **Performance**: Performance issues or optimization opportunities
4. **Code Quality**: Readability, maintainability, and best practices
5. **Testing**: Missing tests or test coverage concerns

Format your response as markdown with clear sections. Be constructive and specific.
For each issue, reference the file and line if possible.

If the code looks good, acknowledge what was done well.

Here is the diff to review:

\`\`\`diff
${DIFF}
\`\`\`"

# Run Copilot CLI
log_step "Running Copilot CLI review..."

REVIEW=$(copilot -p "$PROMPT" --allow-all-tools -s --model "$COPILOT_MODEL" 2>&1)

if [[ -z "$REVIEW" ]]; then
    log_error "Copilot CLI produced no output"
    exit 1
fi

# Format review
FORMATTED_REVIEW="## 🤖 Automated Code Review

${REVIEW}

---
*Generated by Copilot CLI Code Reviewer (local run)*"

# Output
echo ""
echo "=========================================="
echo -e "${GREEN}Code Review Result${NC}"
echo "=========================================="
echo ""
echo "$FORMATTED_REVIEW"
echo ""

# Save to file
OUTPUT_FILE="/tmp/pr-review-${PR_NUMBER}.md"
echo "$FORMATTED_REVIEW" > "$OUTPUT_FILE"
log_info "Review saved to: ${OUTPUT_FILE}"

# Post comment if requested
if [[ "$POST_COMMENT" == "true" ]]; then
    log_step "Posting comment to PR..."

    if command -v gh &> /dev/null; then
        gh pr comment "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --body "$FORMATTED_REVIEW"
        log_info "Comment posted to PR #${PR_NUMBER}"
    else
        log_error "gh CLI required to post comments. Install from https://cli.github.com"
    fi
fi

log_info "Done!"
